### ISSUE TITLE
blocks not supported in spaceless

### ISSUE THREAD

**Issue by ogonkov** [cloudratha/djanjucks#1]
Not sure that it could be solved on the side of the nunjucks parser.

Blocks inside `{% spaceless %}` is not properly recognized as blocks:

```django
{% spaceless %}
  {% block example %}
  <span>Default block content</span>
  {% endblock %}
{% endspaceless %}
```

Code above result to

```
Error: unknown block "example"
```

**Comment by cloudratha** [comment]
I'm not sure I follow. As far as I'm aware, the `spaceless` block removes spaces in-between the blocks. The children still need to be valid markup.

Are you perhaps thinking of the `verbatim` block?

**Comment by ogonkov** [comment]
Nope, look at my commit https://github.com/ogonkov/djanjucks/commit/af44af4a959db5af112d10ea3ff373236aba302f
